# Generated by Django 5.2.14 on 2026-05-13 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('is_default', models.BooleanField(default=False, help_text='Si está marcado, se usa cuando una operación no especifica tipo.')),
                ('calculation_type', models.CharField(choices=[('manual', 'Manual'), ('weighted_combination', 'Combinación ponderada')], default='manual', max_length=30)),
                ('combination_formula', models.JSONField(blank=True, help_text='Solo para tipos ponderados. Ej: {"BNA": 0.7, "CCL": 0.3}.', null=True)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('currency_from', models.ForeignKey(help_text='Moneda de origen del par (ej.: USD).', on_delete=django.db.models.deletion.PROTECT, related_name='rate_types_from', to='currencies.currency')),
                ('currency_to', models.ForeignKey(help_text='Moneda de destino del par (ej.: ARS).', on_delete=django.db.models.deletion.PROTECT, related_name='rate_types_to', to='currencies.currency')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de cotización',
                'verbose_name_plural': 'Tipos de cotización',
                'ordering': ('-is_default', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=15)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('imported', 'Importada'), ('calculated', 'Calculada')], default='manual', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rate_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='pricing.exchangeratetype')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ('-date',),
            },
        ),
        migrations.AddConstraint(
            model_name='exchangeratetype',
            constraint=models.UniqueConstraint(fields=('name',), name='ratetype_unique_name'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['rate_type', '-date'], name='pricing_exc_rate_ty_b6a10c_idx'),
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.UniqueConstraint(fields=('rate_type', 'date'), name='rate_unique_per_type_per_date'),
        ),
    ]
