# Generated by Django 5.2.14 on 2026-05-13 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_supplier_subcontract_trackingcategory_bank_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('currencies', '0002_seed_currencies'),
        ('pricing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=4, max_digits=15)),
                ('effective_date', models.DateField(db_index=True)),
                ('source', models.CharField(choices=[('purchase', 'Compra'), ('manual', 'Manual'), ('import', 'Importado')], default='manual', max_length=20)),
                ('source_purchase_item_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_reference', models.BooleanField(default=True, help_text='Si está marcado, este precio se considera para cálculos de receta. Marcalo en False para precios circunstanciales (ofertas puntuales).')),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='currencies.currency')),
                ('supplier', models.ForeignKey(blank=True, help_text='Proveedor de referencia (no obligatorio).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prices', to='catalog.supplier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Precio',
                'verbose_name_plural': 'Precios',
                'ordering': ('-effective_date', '-created_at'),
                'indexes': [models.Index(fields=['content_type', 'object_id', '-effective_date'], name='pricing_pri_content_a80b09_idx'), models.Index(fields=['-effective_date'], name='pricing_pri_effecti_9b4d20_idx')],
            },
        ),
    ]
