# Generated by Django 5.2.14 on 2026-05-13 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('tax_id', models.CharField(blank=True, max_length=20, verbose_name='CUIT')),
                ('iva_condition', models.CharField(choices=[('responsable_inscripto', 'Responsable Inscripto'), ('monotributo', 'Monotributo'), ('exento', 'Exento')], default='responsable_inscripto', max_length=30)),
                ('iibb_number', models.CharField(blank=True, max_length=30, verbose_name='Nº IIBB')),
                ('fiscal_address', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sociedad',
                'verbose_name_plural': 'Sociedades',
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('tax_id', ''), _negated=True), fields=('tax_id',), name='company_unique_tax_id')],
            },
        ),
    ]
