# Generated by Django 5.2.14 on 2026-05-13 21:08

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_supplier_subcontract_trackingcategory_bank_and_more'),
        ('companies', '0001_initial'),
        ('currencies', '0002_seed_currencies'),
        ('pricing', '0002_price'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_type', models.CharField(choices=[('obra', 'De obra'), ('admin', 'Administrativa'), ('cadeteria', 'Cadetería')], default='obra', max_length=20)),
                ('document_type', models.CharField(choices=[('factura_a', 'Factura A'), ('factura_b', 'Factura B'), ('factura_c', 'Factura C'), ('presupuesto', 'Presupuesto'), ('remito', 'Remito'), ('ticket', 'Ticket'), ('otro', 'Otro')], default='factura_a', max_length=20)),
                ('document_number', models.CharField(blank=True, max_length=50, verbose_name='Nº comprobante')),
                ('invoice_date', models.DateField()),
                ('is_subcontract', models.BooleanField(default=False, help_text='Si es True, la compra entera es un subcontrato. Los ítems se cargan contra Subcontracts.')),
                ('is_itemized', models.BooleanField(default=False, editable=False)),
                ('supplier_email', models.EmailField(blank=True, help_text='Override del mail del catálogo.', max_length=254)),
                ('detail', models.CharField(blank=True, help_text='Descripción libre.', max_length=300)),
                ('main_item_description', models.CharField(blank=True, help_text='Solo si no se abre en ítems.', max_length=300)),
                ('amount_without_tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Monto sin IVA')),
                ('iva_21', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='IVA 21%')),
                ('iva_10_5', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='IVA 10,5%')),
                ('perc_iibb', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Percepción IIBB')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Monto total')),
                ('total_in_ars', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_in_usd_oficial', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_in_usd_ccl', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=80)),
                ('week_to_pay', models.CharField(blank=True, help_text="Ej: '2026-W20'.", max_length=30)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('to_pay', 'A pagar'), ('paid_partial', 'Pagada parcial'), ('paid', 'Pagada'), ('cancelled', 'Cancelada')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('business_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='catalog.businesscomponent')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('exchange_rate_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pricing.exchangerate')),
                ('original_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='currencies.currency')),
                ('project', models.ForeignKey(blank=True, help_text="Obligatorio si purchase_type='obra'.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='projects.project')),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='catalog.rubro')),
                ('subrubro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='catalog.subrubro')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='catalog.supplier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ('-invoice_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_description', models.CharField(blank=True, max_length=300)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('task_id', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='catalog.material')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.purchase')),
                ('subcontract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='catalog.subcontract')),
                ('subrubro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='catalog.subrubro')),
                ('tracking_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='catalog.trackingcategory')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='catalog.unit')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ítem de compra',
                'verbose_name_plural': 'Ítems de compra',
                'ordering': ('purchase', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['company', 'status'], name='procurement_company_15d6de_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['project', '-invoice_date'], name='procurement_project_a8cf49_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['supplier', '-invoice_date'], name='procurement_supplie_856c58_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['status', 'due_date'], name='procurement_status_34624b_idx'),
        ),
    ]
