# Generated by Django 5.2.14 on 2026-05-13 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_seed_currencies'),
        ('pricing', '0002_price'),
        ('procurement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_method', models.CharField(blank=True, max_length=80)),
                ('reference', models.CharField(blank=True, help_text='Nº de transferencia, cheque, etc.', max_length=80, verbose_name='Nº de referencia')),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_payments', to='currencies.currency')),
                ('exchange_rate_used', models.ForeignKey(blank=True, help_text='Solo si la moneda del pago difiere de la moneda de la compra.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pricing.exchangerate')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='procurement.purchase')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ('-payment_date', '-created_at'),
                'indexes': [models.Index(fields=['purchase', '-payment_date'], name='procurement_purchas_2e7379_idx'), models.Index(fields=['payment_date'], name='procurement_payment_735a79_idx')],
            },
        ),
    ]
