# Generated by Django 5.2.14 on 2026-05-14 18:59

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_team_leader_team_updated_by_team_team_unique_name'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('output_unit', models.ForeignKey(help_text='Unidad del resultado (M2, M3, KG…).', on_delete=django.db.models.deletion.PROTECT, related_name='mixes_as_output', to='catalog.unit')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mezcla',
                'verbose_name_plural': 'Mezclas',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MixComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_per_unit', models.DecimalField(decimal_places=4, max_digits=15)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('input_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mix_components_as_input', to='catalog.unit')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mix_components', to='catalog.material')),
                ('mix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='task_master.mix')),
                ('sub_mix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_in_mix_components', to='task_master.mix')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Componente de mezcla',
                'verbose_name_plural': 'Componentes de mezcla',
                'ordering': ('mix', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, help_text='Jerárquico opcional (ej.: A.1.5). Auto-generable en futuro.', max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, verbose_name='Detalle')),
                ('active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('output_unit', models.ForeignKey(help_text='Unidad de la Tarea (UT).', on_delete=django.db.models.deletion.PROTECT, related_name='tasks_as_output', to='catalog.unit')),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='catalog.rubro')),
                ('subrubro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='catalog.subrubro')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ('code', 'name'),
            },
        ),
        migrations.CreateModel(
            name='TaskComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('material', 'Material'), ('labor', 'Mano de obra'), ('subcontract', 'Subcontrato'), ('sub_mix', 'Sub-mezcla'), ('sub_task', 'Sub-tarea')], max_length=20)),
                ('classification', models.CharField(choices=[('materials', 'Materiales'), ('labor', 'Mano de obra')], default='materials', max_length=20)),
                ('quantity_per_unit', models.DecimalField(decimal_places=4, max_digits=15)),
                ('detail', models.CharField(blank=True, max_length=200)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('input_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_components_as_input', to='catalog.unit')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_components', to='catalog.material')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_components', to='catalog.position')),
                ('sub_mix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_components_as_sub_mix', to='task_master.mix')),
                ('sub_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_in_task_components', to='task_master.task')),
                ('subcontract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_components', to='catalog.subcontract')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='task_master.task')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Componente de tarea',
                'verbose_name_plural': 'Componentes de tarea',
                'ordering': ('task', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TaskAdjustmentSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('suggested_quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('sample_size', models.PositiveIntegerField(default=0)),
                ('variance_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('based_on_projects', models.ManyToManyField(blank=True, related_name='task_adjustment_suggestions', to='projects.project')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustment_suggestions', to='task_master.task')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_suggestions', to='task_master.taskcomponent')),
            ],
            options={
                'verbose_name': 'Sugerencia de ajuste',
                'verbose_name_plural': 'Sugerencias de ajuste',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='mix',
            constraint=models.UniqueConstraint(fields=('name',), name='mix_unique_name'),
        ),
        migrations.AddConstraint(
            model_name='mix',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('code',), name='mix_unique_code'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('name',), name='task_unique_name'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('code',), name='task_unique_code'),
        ),
    ]
