# Generated by Django 5.2.14 on 2026-05-15 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_bankaccount'),
        ('companies', '0001_initial'),
        ('currencies', '0002_seed_currencies'),
        ('payroll', '0004_socialchargespayment'),
        ('pricing', '0002_price'),
        ('procurement', '0002_purchasepayment'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreasuryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('income', 'Ingreso'), ('expense', 'Egreso'), ('transfer', 'Transferencia'), ('currency_exchange', 'Cambio de moneda')], max_length=20)),
                ('category', models.CharField(choices=[('supplier_payment', 'Pago a proveedor'), ('payroll_payment', 'Pago de nómina'), ('social_charges_payment', 'Carga social'), ('taxes', 'Impuestos'), ('financing', 'Financiamiento'), ('admin', 'Administrativo'), ('client_payment', 'Cobro cliente'), ('client_advance', 'Anticipo cliente'), ('transfer', 'Transferencia interna'), ('currency_exchange', 'Cambio de moneda'), ('other', 'Otro')], default='other', max_length=30)),
                ('date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('counterpart_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('bank_account', models.ForeignKey(blank=True, help_text='Si no se carga, el movimiento es en efectivo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treasury_entries', to='catalog.bankaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treasury_entries', to='companies.company')),
                ('counterpart_account', models.ForeignKey(blank=True, help_text='Cuenta destino para transferencias y cambios de moneda.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='counterpart_treasury_entries', to='catalog.bankaccount')),
                ('counterpart_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='counterpart_treasury_entries', to='currencies.currency')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treasury_entries', to='currencies.currency')),
                ('exchange_rate_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pricing.exchangerate')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_entries', to='projects.project')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_treasury_entries', to=settings.AUTH_USER_MODEL)),
                ('source_payroll_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_entries', to='payroll.payrollperiod')),
                ('source_purchase_payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_entry', to='procurement.purchasepayment')),
                ('source_social_charges_payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_entry', to='payroll.socialchargespayment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento financiero',
                'verbose_name_plural': 'Movimientos financieros',
                'ordering': ('-date', '-created_at'),
                'indexes': [models.Index(fields=['company', '-date'], name='treasury_tr_company_f0d76c_idx'), models.Index(fields=['bank_account', '-date'], name='treasury_tr_bank_ac_dc8b9c_idx'), models.Index(fields=['category', '-date'], name='treasury_tr_categor_8a2f2b_idx'), models.Index(fields=['project', '-date'], name='treasury_tr_project_165156_idx'), models.Index(fields=['is_reconciled'], name='treasury_tr_is_reco_453df1_idx')],
            },
        ),
    ]
