# Generated by Django 5.2.14 on 2026-05-14 20:21

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0002_seed_currencies'),
        ('pricing', '0002_price'),
        ('projects', '0001_initial'),
        ('task_master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=160)),
                ('version', models.PositiveIntegerField(default=1, help_text='Versión: 1 = P1, 2 = P2, etc.')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('submitted', 'Presentado'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('superseded', 'Reemplazado')], default='draft', max_length=20)),
                ('pricing_date', models.DateField(blank=True, help_text='Fecha de los precios usados al congelar.', null=True)),
                ('exchange_rate_value', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('total_in_ars', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_in_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('materials_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('subcontracts_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('margin_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Markup que se suma al subtotal para llegar al total con margen.', max_digits=6)),
                ('total_with_margin', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_budgets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='currencies.currency')),
                ('exchange_rate_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='pricing.exchangeratetype')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'ordering': ('-project', '-version'),
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_version', models.PositiveIntegerField(default=1, help_text='Versión del Task usada al congelar.')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('materials_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('subcontracts_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('recipe_snapshot', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='budgets.budget')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_items', to='task_master.task')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ítem de presupuesto',
                'verbose_name_plural': 'Ítems de presupuesto',
                'ordering': ('budget', 'order', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['project', 'status'], name='budgets_bud_project_921b10_idx'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('project', 'version'), name='budget_unique_version_per_project'),
        ),
        migrations.AddConstraint(
            model_name='budgetitem',
            constraint=models.UniqueConstraint(fields=('budget', 'task'), name='budgetitem_unique_task_per_budget'),
        ),
    ]
