# Generated by Django 5.2.14 on 2026-05-14 20:44

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0001_initial'),
        ('currencies', '0002_seed_currencies'),
        ('pricing', '0002_price'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetVsActualReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cutoff_date', models.DateField(help_text='Fecha de corte: solo se consideran compras y quincenas hasta esta fecha.')),
                ('total_planned', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_actual', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('variance_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('variance_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Breakdown navegable por rubro y tarea.')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actual_reports', to='budgets.budget')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('in_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_actual_reports', to='currencies.currency')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_actual_reports', to='projects.project')),
                ('rate_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_actual_reports', to='pricing.exchangeratetype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cruce Presupuesto vs Real',
                'verbose_name_plural': 'Cruces Presupuesto vs Real',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['project', '-created_at'], name='budget_anal_project_5040a8_idx'), models.Index(fields=['budget', '-created_at'], name='budget_anal_budget__6cfded_idx')],
            },
        ),
    ]
