# Generated by Django 5.2.14 on 2026-05-15 11:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0002_seed_currencies'),
        ('projects', '0001_initial'),
        ('task_master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('forecast_date', models.DateField()),
                ('forecasted_total_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('forecasted_completion_date', models.DateField(blank=True, null=True)),
                ('forecasted_social_charges', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Previsión',
                'verbose_name_plural': 'Previsiones',
                'ordering': ('-forecast_date',),
            },
        ),
        migrations.CreateModel(
            name='ProjectExecutionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot_date', models.DateField(db_index=True)),
                ('total_materials_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_labor_internal_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_labor_subcontract_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_social_charges_real', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_social_charges_estimated', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('breakdown', models.JSONField(blank=True, default=dict, help_text='Desglose por rubro/subrubro/task (JSON serializable).')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execution_snapshots', to='currencies.currency')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_snapshots', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Snapshot de obra',
                'verbose_name_plural': 'Snapshots de obra',
                'ordering': ('-snapshot_date', '-created_at'),
                'indexes': [models.Index(fields=['project', '-snapshot_date'], name='tracking_pr_project_308fec_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'snapshot_date'), name='snapshot_unique_per_project_per_date')],
            },
        ),
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_version', models.PositiveIntegerField(default=1)),
                ('planned_quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15)),
                ('actual_quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15)),
                ('planned_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('actual_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('completion_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('status', models.CharField(choices=[('not_started', 'No iniciada'), ('in_progress', 'En curso'), ('completed', 'Completada')], default='not_started', max_length=20)),
                ('last_computed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_executions', to='projects.project')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='task_master.task')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ejecución de tarea',
                'verbose_name_plural': 'Ejecuciones de tarea',
                'ordering': ('project', 'task'),
                'constraints': [models.UniqueConstraint(fields=('project', 'task'), name='taskexecution_unique_task_per_project')],
            },
        ),
    ]
