# Generated by Django 5.2.14 on 2026-05-15 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_team_leader_team_updated_by_team_team_unique_name'),
        ('companies', '0001_initial'),
        ('currencies', '0002_seed_currencies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('cbu', models.CharField(blank=True, max_length=22, verbose_name='CBU')),
                ('alias', models.CharField(blank=True, max_length=80)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='catalog.bank')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='currencies.currency')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuenta bancaria',
                'verbose_name_plural': 'Cuentas bancarias',
                'ordering': ('order', 'name'),
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('account_number', ''), _negated=True), fields=('bank', 'company', 'account_number'), name='bankaccount_unique_per_bank_company')],
            },
        ),
    ]
