# Generated by Django 5.2.14 on 2026-05-13 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_team'),
        ('companies', '0001_initial'),
        ('currencies', '0002_seed_currencies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internal_id', models.CharField(blank=True, help_text='ID interno (numeración propia de la org).', max_length=30)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('arca_registered', models.BooleanField(default=False, verbose_name='Alta en ARCA/AFIP')),
                ('last_known_salary', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('boss', models.ForeignKey(blank=True, help_text='Jefe directo / Jefe de Obra.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='payroll.employee')),
                ('company', models.ForeignKey(help_text='Sociedad que paga el sueldo.', on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_known_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='currencies.currency')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='catalog.position')),
                ('primary_rubro', models.ForeignKey(blank=True, help_text='Solo informativo — sugerencia de imputación principal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_employees', to='catalog.rubro')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='catalog.employeestatus')),
                ('teams', models.ManyToManyField(blank=True, help_text='Equipos a los que pertenece. Puede estar en varios.', related_name='members', to='catalog.team')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ('-hire_date', 'id'),
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=160)),
                ('relationship', models.CharField(blank=True, help_text='Esposo/a, padre, madre, hermano/a, etc.', max_length=80)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='payroll.employee')),
            ],
            options={
                'verbose_name': 'Contacto de emergencia',
                'verbose_name_plural': 'Contactos de emergencia',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='EmployeeBanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cbu', models.CharField(blank=True, max_length=22, verbose_name='CBU')),
                ('cvu_mercado_libre', models.CharField(blank=True, help_text='Mercado Pago / billeteras virtuales.', max_length=22, verbose_name='CVU billetera virtual')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_banking', to='catalog.bank')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banking', to='payroll.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Datos bancarios',
                'verbose_name_plural': 'Datos bancarios',
            },
        ),
        migrations.CreateModel(
            name='EmployeePersonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('nationality', models.CharField(blank=True, max_length=80)),
                ('document_type', models.CharField(choices=[('DNI', 'DNI'), ('PAS', 'Pasaporte'), ('OTHER', 'Otro')], default='DNI', max_length=10)),
                ('document_number', models.CharField(blank=True, max_length=30)),
                ('cuil', models.CharField(blank=True, max_length=20, verbose_name='CUIL')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Soltero/a'), ('married', 'Casado/a'), ('divorced', 'Divorciado/a'), ('widowed', 'Viudo/a'), ('other', 'Otro')], max_length=20)),
                ('children_count', models.PositiveIntegerField(default=0)),
                ('phone_landline', models.CharField(blank=True, max_length=40, verbose_name='Teléfono fijo')),
                ('phone_mobile', models.CharField(blank=True, max_length=40, verbose_name='Celular')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_data', to='payroll.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Datos personales',
                'verbose_name_plural': 'Datos personales',
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['company', 'status'], name='payroll_emp_company_8824a5_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['position'], name='payroll_emp_positio_28ae1b_idx'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('internal_id', ''), _negated=True), fields=('company', 'internal_id'), name='employee_unique_internal_id_per_company'),
        ),
    ]
