# Generated by Django 5.2.14 on 2026-05-13 22:31

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_team_leader_team_updated_by_team_team_unique_name'),
        ('companies', '0001_initial'),
        ('currencies', '0002_seed_currencies'),
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_number', models.PositiveSmallIntegerField(help_text='1 o 2 (primera o segunda quincena del mes).')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('talonario_name', models.CharField(blank=True, help_text='Ej: "1era Quincena de Diciembre".', max_length=120)),
                ('working_days', models.PositiveSmallIntegerField(default=10, help_text='Días laborales L-V.')),
                ('saturdays', models.PositiveSmallIntegerField(default=2)),
                ('holidays', models.PositiveSmallIntegerField(default=0)),
                ('total_days', models.PositiveSmallIntegerField(default=12)),
                ('hours_weekday', models.PositiveSmallIntegerField(default=8)),
                ('hours_saturday', models.PositiveSmallIntegerField(default=7)),
                ('total_hours', models.PositiveSmallIntegerField(default=94)),
                ('plus_overtime_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('plus_presentismo_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('closed', 'Cerrada'), ('paid', 'Pagada')], default='open', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_periods', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quincena',
                'verbose_name_plural': 'Quincenas',
                'ordering': ('-year', '-month', '-period_number'),
            },
        ),
        migrations.CreateModel(
            name='PayrollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_snapshot', models.CharField(blank=True, max_length=120)),
                ('team_snapshot', models.CharField(blank=True, max_length=200)),
                ('boss_snapshot', models.CharField(blank=True, max_length=120)),
                ('position_snapshot', models.CharField(blank=True, max_length=120)),
                ('primary_rubro_snapshot', models.CharField(blank=True, max_length=120)),
                ('suspended', models.BooleanField(default=False, help_text='Suspendido en esta quincena puntual.')),
                ('value_jornal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('days_worked', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('absences', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Faltas')),
                ('justified_absences', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Justificadas')),
                ('vacations', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Vacaciones (días)')),
                ('vacations_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('vacations_detail', models.CharField(blank=True, max_length=200)),
                ('late_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='H. tarde')),
                ('late_hours_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('late_hours_detail', models.CharField(blank=True, max_length=200)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='H. extra')),
                ('overtime_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('attendance_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('hours_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('extraordinary_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Suma de extraordinarios (Turno C).', max_digits=15)),
                ('presentismo_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('gross', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('net', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('bank_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('cash_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('bills_1000', models.PositiveIntegerField(default=0)),
                ('bills_500', models.PositiveIntegerField(default=0)),
                ('bills_200', models.PositiveIntegerField(default=0)),
                ('bills_100', models.PositiveIntegerField(default=0)),
                ('bills_50', models.PositiveIntegerField(default=0)),
                ('bills_20', models.PositiveIntegerField(default=0)),
                ('bills_10', models.PositiveIntegerField(default=0)),
                ('bills_manual_override', models.BooleanField(default=False, help_text='Si está marcado, no recalcular los billetes desde cash_amount.')),
                ('receipt_observations', models.CharField(blank=True, help_text='Aparece en el recibo.', max_length=300)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_entries', to='currencies.currency')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_entries', to='payroll.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='payroll.payrollperiod')),
            ],
            options={
                'verbose_name': 'Entrada de quincena',
                'verbose_name_plural': 'Entradas de quincena',
                'ordering': ('payroll_period', 'employee_id'),
            },
        ),
        migrations.CreateModel(
            name='PositionPlus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='position_pluses', to='currencies.currency')),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_pluses', to='payroll.payrollperiod')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='period_pluses', to='catalog.position')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plus por puesto',
                'verbose_name_plural': 'Plus por puesto',
            },
        ),
        migrations.AddConstraint(
            model_name='payrollperiod',
            constraint=models.UniqueConstraint(fields=('company', 'year', 'month', 'period_number'), name='payrollperiod_unique_per_company'),
        ),
        migrations.AddConstraint(
            model_name='payrollentry',
            constraint=models.UniqueConstraint(fields=('payroll_period', 'employee'), name='payrollentry_unique_employee_per_period'),
        ),
        migrations.AddConstraint(
            model_name='positionplus',
            constraint=models.UniqueConstraint(fields=('payroll_period', 'position'), name='positionplus_unique_per_period_position'),
        ),
    ]
