# Generated by Django 5.2.14 on 2026-05-13 23:04

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_team_leader_team_updated_by_team_team_unique_name'),
        ('payroll', '0002_payrollperiod_payrollentry_positionplus_and_more'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollExtraordinary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Cantidad (ej.: días de Presentismo). Opcional.', max_digits=8, null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_extraordinaries', to='catalog.extraordinaryconcept')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payroll_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraordinaries', to='payroll.payrollentry')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Extraordinario',
                'verbose_name_plural': 'Extraordinarios',
                'ordering': ('payroll_entry_id', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PayrollAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_id', models.PositiveIntegerField(blank=True, null=True)),
                ('pct', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Porcentaje del jornal (0–100).', max_digits=5, verbose_name='% de la jornada')),
                ('jornal_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('social_charges_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('social_charges_status', models.CharField(choices=[('estimated', 'Estimado'), ('real', 'Real')], default='estimated', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payroll_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='payroll.payrollentry')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_allocations', to='projects.project')),
                ('subrubro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_allocations', to='catalog.subrubro')),
                ('tracking_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_allocations', to='catalog.trackingcategory')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imputación a obra',
                'verbose_name_plural': 'Imputaciones a obras',
                'ordering': ('payroll_entry_id', 'id'),
                'indexes': [models.Index(fields=['project', 'payroll_entry'], name='payroll_pay_project_cdeaf7_idx')],
            },
        ),
    ]
