# Generated by Django 5.2.14 on 2026-05-15 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('importer_slug', models.CharField(max_length=60)),
                ('importer_label', models.CharField(max_length=120)),
                ('filename', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('dry_run', 'Vista previa'), ('committed', 'Confirmado'), ('failed', 'Fallido')], max_length=20)),
                ('rows_total', models.PositiveIntegerField(default=0)),
                ('rows_ok', models.PositiveIntegerField(default=0)),
                ('rows_error', models.PositiveIntegerField(default=0)),
                ('rows_created', models.PositiveIntegerField(default=0)),
                ('rows_updated', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list, help_text='Lista de errores por fila: [{row, message}, ...]')),
                ('summary', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Importación',
                'verbose_name_plural': 'Importaciones',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['importer_slug', '-created_at'], name='imports_imp_importe_8be330_idx')],
            },
        ),
    ]
